2023-06-01 15:24:24.990 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:24:24.997 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:24:25.004 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:24:25.009 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ssh_command which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:24:25.015 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration python_script which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:24:25.021 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dataplicity which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-01 15:25:08.851 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'tlg_system_start' could not be validated and has been disabled: template value should be a string for dictionary value @ data['action'][2]['data']. Got {'message': "*Хост*\nПроцессор: \nОЗУ:\nДиск:\nSwap:\n\n*Home Assistant*\nСвичей недоступно:\nСветильников недоступно:\nСенсоров недоступно:\nБинарных сенсоров недоступно:\n\nСостояние за: {{ states(''sensor.date_time'') }}"}
2023-06-01 15:25:12.728 WARNING (MainThread) [homeassistant.components.number] custom_components.xiaomi_miot_raw.number::MiotNumberInput is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2023-06-01 15:25:37.574 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-06-01 15:25:37.580 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-06-01 15:25:37.586 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-06-01 15:25:37.592 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-06-01 15:25:52.881 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states('sensor.0x00158d0001e09b81_pressure')|float / 1.334)|round(1) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1893, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 544, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2164, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1896, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1594, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (states('sensor.0x00158d0001e09b81_pressure')|float / 1.334)|round(1) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 665, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 546, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (states('sensor.0x00158d0001e09b81_pressure')|float / 1.334)|round(1) }}' but no default was specified
2023-06-01 15:25:52.924 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (states('sensor.0x00158d0001e09b81_pressure')|float / 1.334)|round(1) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.0x00158d0001e09b81_pressure')|float / 1.334)|round(1) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.0x00158d0001e09b81_pressure_mmhg'
2023-06-01 15:30:00.415 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.router_disk, topic: 'router/disk' with payload: b'Filesystem                Size      Used Available Use% Mounted on\nrootfs                  248.0M     36.9M    198.2M  16% /\n/dev/root                 3.0M      3.0M         0 100% /rom\ntmpfs                    14.3M      1.2M     13.0M   9% /tmp\n/dev/sda2               248.0M     36.9M    198.2M  16% /overlay\noverlayfs:/overlay      248.0M     36.9M    198.2M  16% /\ntmpfs                   512.0K         0    512.0K   0% /dev'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 706, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1576, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1225, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.router_disk. State max length is 255 characters.
2023-06-01 15:30:55.719 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 15:30:55.744 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 15:33:15.741 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 15:33:15.747 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 15:37:15.770 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 15:37:15.780 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 15:46:05.873 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 15:46:05.882 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 16:00:02.737 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.router_disk, topic: 'router/disk' with payload: b'Filesystem                Size      Used Available Use% Mounted on\nrootfs                  248.0M     36.9M    198.2M  16% /\n/dev/root                 3.0M      3.0M         0 100% /rom\ntmpfs                    14.3M      1.2M     13.0M   9% /tmp\n/dev/sda2               248.0M     36.9M    198.2M  16% /overlay\noverlayfs:/overlay      248.0M     36.9M    198.2M  16% /\ntmpfs                   512.0K         0    512.0K   0% /dev'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 706, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1576, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1225, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.router_disk. State max length is 255 characters.
2023-06-01 16:01:16.007 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:01:16.014 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 16:07:26.035 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:07:26.045 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:11:26.080 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:11:26.088 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:14:46.112 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:14:46.121 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:16:24.091 ERROR (MainThread) [frontend.js.latest.202305033] https://victimized-toucan-3591.dataplicity.io/frontend_latest/core-hpNqcTVzWqI.js:1:9860 Uncaught Error: Suspend promise not set
2023-06-01 16:16:25.080 ERROR (MainThread) [frontend.js.latest.202305033] https://victimized-toucan-3591.dataplicity.io/frontend_latest/core-hpNqcTVzWqI.js:1:9860 Uncaught Error: Suspend promise not set
2023-06-01 16:16:26.144 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 16:16:26.153 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:16:36.128 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:16:36.137 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:17:06.132 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:17:06.138 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:18:56.146 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:18:56.156 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:18:56.187 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 16:18:56.197 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:19:31.159 ERROR (MainThread) [custom_components.xiaomi_miot_raw.basic_dev_class] Got exception while fetching Light sofa 's state: Unable to discover the device 192.168.2.129
2023-06-01 16:21:56.218 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:21:56.238 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 16:22:36.182 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:22:36.189 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:28:06.295 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:28:06.307 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 16:30:02.811 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.router_disk, topic: 'router/disk' with payload: b'Filesystem                Size      Used Available Use% Mounted on\nrootfs                  248.0M     36.9M    198.2M  16% /\n/dev/root                 3.0M      3.0M         0 100% /rom\ntmpfs                    14.3M      1.2M     13.0M   9% /tmp\n/dev/sda2               248.0M     36.9M    198.2M  16% /overlay\noverlayfs:/overlay      248.0M     36.9M    198.2M  16% /\ntmpfs                   512.0K         0    512.0K   0% /dev'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 706, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1576, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1225, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.router_disk. State max length is 255 characters.
2023-06-01 16:46:36.477 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:46:36.488 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 16:49:06.531 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:49:06.537 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 16:52:46.536 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:52:46.546 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 16:55:06.582 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 16:55:06.591 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 17:00:02.832 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.router_disk, topic: 'router/disk' with payload: b'Filesystem                Size      Used Available Use% Mounted on\nrootfs                  248.0M     36.9M    198.2M  16% /\n/dev/root                 3.0M      3.0M         0 100% /rom\ntmpfs                    14.3M      1.2M     13.0M   9% /tmp\n/dev/sda2               248.0M     36.9M    198.2M  16% /overlay\noverlayfs:/overlay      248.0M     36.9M    198.2M  16% /\ntmpfs                   512.0K         0    512.0K   0% /dev'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 706, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1576, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1225, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.router_disk. State max length is 255 characters.
2023-06-01 17:01:06.643 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 17:01:06.652 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:01:46.628 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 17:01:46.638 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:07:56.665 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 17:07:56.675 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:16:56.806 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:16:56.815 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 17:23:06.801 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:23:06.807 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e67c5bf5 is taking over 10 seconds
2023-06-01 17:23:16.860 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:23:16.869 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 17:25:16.874 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:25:16.883 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
2023-06-01 17:28:06.925 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:28:06.934 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6d89786 is taking over 10 seconds
2023-06-01 17:30:02.774 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.router_disk, topic: 'router/disk' with payload: b'Filesystem                Size      Used Available Use% Mounted on\nrootfs                  248.0M     36.9M    198.2M  16% /\n/dev/root                 3.0M      3.0M         0 100% /rom\ntmpfs                    14.3M      1.2M     13.0M   9% /tmp\n/dev/sda2               248.0M     36.9M    198.2M  16% /overlay\noverlayfs:/overlay      248.0M     36.9M    198.2M  16% /\ntmpfs                   512.0K         0    512.0K   0% /dev'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 706, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1576, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1225, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.router_disk. State max length is 255 characters.
2023-06-01 17:32:06.923 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miot_raw switch took longer than the scheduled update interval 0:00:10
2023-06-01 17:32:06.930 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.212a01_5448e6e68e77 is taking over 10 seconds
